### ISSUE TITLE
make can't find ac_arith_coder.h

### ISSUE THREAD

**Issue by 1Andrew** [mstorsjo/fdk-aac#100]
Trying to compile from Windows 7.
Running  build_libfdk_aac.bat terminates with:

libAACdec/src/channelinfo.h:127:28: fatal error: ac_arith_coder.h: No such file or directory

 #include "ac_arith_coder.h"

compilation terminated.
make: *** [libAACdec/src/aacdecoder.o] Error 1

**Comment by mstorsjo** [comment]
Which `build_libfdk_aac.bat` is that? This sounds like some build system that isn't updated for the new details in fdk-aac 2.0.0, where there's a couple new directories added.

**Comment by 1Andrew** [comment]
how can I identify the build of a bat file?

All I wan to do is compile the latest fdk-aac for windows, on my windows 
7 or 10 machine, or possibly my linux box.

Would you mind pointing me to any howto's or perhaps the most recent bat 
files?

Thanks for your time, any help is appreciated.

Andrew
*From:* Martin Storsjö <mailto:notifications@github.com>
*Sent:* Wednesday, December 12, 2018 2:59 PM
*To:* mstorsjo/fdk-aac <mailto:fdk-aac@noreply.github.com>
*Cc:* 1Andrew <mailto:andrew.r.leith@gmail.com> ; Author 
<mailto:author@noreply.github.com>
*Subject:* Re: [mstorsjo/fdk-aac] make can't find ac_arith_coder.h (#100)

Which |build_libfdk_aac.bat| is that? This sounds like some build system 
that isn't updated for the new details in fdk-aac 2.0.0, where there's a 
couple new directories added.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/mstorsjo/fdk-aac/issues/100#issuecomment-446723350>, 
or mute the thread

**Comment by mstorsjo** [comment]
So the issue is, I don't provide any `build_libfdk_aac.bat`, so whoever provided this to you should fix it to work with the latest version of fdk-aac.

I presume that you have got it from https://github.com/nu774/fdkaac_autobuild. That repo seems to have a makefile that hasn't been updated in sync with the latest version - that's where the issue lies.
