### ISSUE TITLE
[q] VBR mode status?

### ISSUE THREAD

**Issue by tico-tico** [mstorsjo/fdk-aac#104]
Hi.

I see that some programs which use fdk-aac (like ffmpeg for instance), inform user that VBR mode is unsupported, but I failed to find anything about this "unsupportness" in this repository on in the upstream. Can you confirm that VBR is broken somehow (I mean sound-wise) or it's just another urban legend.

Thanks.

**Comment by tico-tico** [comment]
Hm, that's interesting, thanks. I was confused why it's unsupported if I clearly can see VBR mentioned in *aacenc_lib.h* in the upstream. At this point I will read *unsupported* as *unpredictable* then.

Thanks again.

**Comment by mstorsjo** [comment]
Yep - even though VBR is mentioned in aacenc_lib.h in the upstream, I needed to do a change like https://github.com/mstorsjo/fdk-aac/commit/b431d100a3582652dfd11b2e08ffb6c8f05bfd41 in order to be able to set it.

**Comment by tico-tico** [comment]
But this is in upstream already

```
    case AACENC_BITRATEMODE:
      if (settings->userBitrateMode != value) {
        switch (value) {
          case 0:
          case 1:
          case 2:
          case 3:
          case 4:
          case 5:
            settings->userBitrateMode = value;
            hAacEncoder->InitFlags |=
                AACENC_INIT_CONFIG | AACENC_INIT_TRANSPORT;
            break;
          default:
            err = AACENC_INVALID_CONFIG;
            break;
        } /* switch value */
      }
```

Or i am confusing something again.

**Comment by mstorsjo** [comment]
Oh, I hadn't noticed that. While digging through history, this seems to have become enabled in the upstream source in https://github.com/mstorsjo/fdk-aac/commit/e1c78ed73faa51f2c7fcb0c4a17a92be9cc747f5, so a couple years ago.

Still, the same restrictions about not all modes being available in all settings do apply though, afaik.
