### ISSUE TITLE
Retrieve version-string on shallow clone

### ISSUE THREAD

**Issue by Reino17** [mstorsjo/fdk-aac#107]
Hello Martin,

The following isn't particularly a fdk-aac question. I hope you don't mind.
```
git describe --tags
v2.0.0-185-gcc5c85d
```
I'm using this command to add the version-string to the archive filename of the (cross)compiled `libfdk-aac-2.dll`.

I noticed however that this tag / information isn't cloned / copied when I'm doing a shallow clone, `git clone --depth 1 https://github.com/mstorsjo/fdk-aac.git`
```
git describe --tags
fatal: No names found, cannot describe anything.
```
I've tried a couple of things, like for instance...
```
git fetch --depth 1 origin tag v2.0.0
remote: Enumerating objects: 168, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 86 (delta 67), reused 20 (delta 2), pack-reused 0
Unpacking objects: 100% (86/86), done.
From https://github.com/mstorsjo/fdk-aac
 * [new tag]         v2.0.0     -> v2.0.0

git describe --tags
fatal: No tags can describe 'cc5c85dd70f04178abccfd2c5539b13e01da78d8'.
Try --always, or create some tags.
```
...but nothing worked so far. I can't seem to find anything similar / related on the internet either.

Do you know how to retrieve the version-string after having done a shallow clone by any chance? If it's possible at all of course. Thanks!

**Comment by mstorsjo** [comment]
Clearly not fdk-aac specific - but I'll bite anyway :-)

I don't think so. As you have a shallow clone, you don't know how the currently checked out revision relates to the fetched tag; the only way to do that would be if you actually had checked out the tag, or if the shallow-ish repo had all commits between the relevant tag and the currently checked out revision.

To find that effectively, you'd pretty much need to ask the remote to describe a given commit, but I don't think there's such functionaly.

I'd suggest posting this question to the git mailing list (git@vger.kernel.org) as they're probably the ones who know best what's possible now and in the potential future. And they're usually kind to sincere questions.

**Comment by Reino17** [comment]
Thanks for your reply, Martin. I subscribed to git@vger.kernel.org and sent [my question](https://www.spinics.net/lists/git/msg365495.html).

In the end it seems to be impossible.  
While `git describe --tags` on a full clone returns `v2.0.0-185-gcc5c85d`, `git ls-remote --tags --refs https://github.com/mstorsjo/fdk-aac.git | tail -n1 | cut -d/ -f3-` on the remote repo only returns the tag `v2.0.0`.

The only minimum way for a local repo and `git describe --tags` to return `v2.0.0-185-gcc5c85d` is to clone everything from `v2.0.0` onward: `git clone --depth 185 https://github.com/mstorsjo/fdk-aac.git` (clone with the history of the last 185 commits). But obviously though this amount of `185` is exactly the thing you don't know beforehand.
