### ISSUE TITLE
How to decode a he-aac file?

### ISSUE THREAD

**Issue by wsygzyr** [mstorsjo/fdk-aac#11]
I want to decode a he-aac(generated from aac-enc.c in the fdk-aac) file ,and I followed the pdf,wrote a program. But the output was not correct. 

Here is my code .
        HANDLE_AACDECODER handle;
    handle  = aacDecoder_Open(TT_MP4_ADTS,1);
    FILE _aacFile = fopen(infile ,"rb");
    HANDLE_WAV wav;
    UCHAR *inBuffer = (UCHAR_)malloc(2048);
    int readLen = -1;
    int _pReadLen = &readLen;
    UINT bytesValid = 0;
    INT_PCM outBuffer[20480];
    int outSize = 0;
    int firstFrame = 1;
    int total = 0;
    while(readLen != 0)
    {
        if (bytesValid != 2048)
        {
            readLen = fread((char_)(inBuffer + bytesValid) , 1, 2048 - bytesValid ,aacFile);
        }
        bytesValid = readLen;
        total += readLen;
        aacDecoder_Fill(handle, &inBuffer, (UINT_)&readLen, &bytesValid);
        AAC_DECODER_ERROR errStatus;
        while ((errStatus = aacDecoder_DecodeFrame(handle,outBuffer ,20480 ,0)) != AAC_DEC_NOT_ENOUGH_BITS)
        {
            CStreamInfo_ info =aacDecoder_GetStreamInfo(handle);
            aacDecoder_SetParam()
            if (firstFrame == 1)
            {
                WAV_OutputOpen(&wav ,outfile ,info->aacSampleRate ,info->numChannels ,16);
                firstFrame = 0;
            }
            WAV_OutputWrite(wav ,(void*)outBuffer ,info->frameSize ,16 ,1);
        }

```
    if (errStatus != AAC_DEC_OK)
    {
        if (errStatus == AAC_DEC_NOT_ENOUGH_BITS)
        {
            continue;
        }
        break;
    }

}
WAV_OutputClose(&wav);
fclose(aacFile);
aacDecoder_Close(handle); 
```

In the pdf ,there is a main.cpp file for the decode,but I can't find it.
By the way , I used aac-enc.c to encode a mono wav using he-aac, but the output file is stereo aac.How can I change it to mono output?
Thank you ~~

**Comment by ValZapod** [comment]
> This is not an encoder issue but an issue with the decoders.

This is not an issue, the consensus is to use stereo for mono since it can be 100 samples in that it wsill become stereo, like in:

http://fate-suite.ffmpeg.org/aac/al_sbr_ps_06_new.mp4

FFmpeg now warns about it (use -v debug)
https://github.com/FFmpeg/FFmpeg/commit/6406d5e430953085a0100b44dd8fceb478b383e2
