### ISSUE TITLE
where is mpegFileRead_Read() ?

### ISSUE THREAD

**Issue by jiemojiemo** [mstorsjo/fdk-aac#112]
Hi guys!
I want to use fdk-aac to decode audio file, but I cannot find mpegFileRead_Read.
Please help me。
![image](https://user-images.githubusercontent.com/13779459/69324064-c2b2c900-0c82-11ea-9499-3e9b5761c145.png)

**Comment by mstorsjo** [comment]
I guess the comment is outdated. I don't know what function would be the corresponding current one.
