### ISSUE TITLE
tag 2.0.2 release

### ISSUE THREAD

**Issue by Be-ing** [mstorsjo/fdk-aac#130]
I have opened a [pull request for vcpkg](https://github.com/microsoft/vcpkg/pull/16007) to update to the current master branch which added CMake support (#119) and support in vcpkg to build the [fork with HE-AAC removed](https://gitlab.freedesktop.org/wtaymans/fdk-aac-stripped/-/merge_requests/1). Could you tag a new release so vcpkg can have a released version instead building commit hashes?

**Comment by Be-ing** [comment]
ping

**Comment by mstorsjo** [comment]
Sure, I can try to make a release sometime soon, but it doesn't happen in a whim

**Comment by Be-ing** [comment]
Thanks. Just wanted to make sure this issue was noticed.

**Comment by mstorsjo** [comment]
Ok, now a 2.0.2 release is out (tag exists in git here, and a tarball available at https://sourceforge.net/projects/opencore-amr/files/fdk-aac/).
