### ISSUE TITLE
How to use the CL command of vs2019 to compile the latest code

### ISSUE THREAD

**Issue by Dopa4** [mstorsjo/fdk-aac#135]
How to use the CL command of vs2019 to compile the latest code

**Comment by mstorsjo** [comment]
You configure it with CMake, either generating visual studio project files, nmake files or ninja build files, and build using either of those tools.

**Comment by Dopa4** [comment]
I remember there was makefile.vc in the FDK AAC folder before. Just use nmake. Now there is no makefile.vc file, how to generate makefile.vc

**Comment by mstorsjo** [comment]
Yes, the nmake file is removed as it's an extra maintainance cost, as cmake can produce the same.

You can do `cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..\fdk-aac` (or maybe leave out the last argument if you build in the source dir) which generates a `Makefile`, then just run `nmake` and it should build the library for you. See CMakeLists.txt for some more hints about how you can configure it.

**Comment by Dopa4** [comment]
![image](https://user-images.githubusercontent.com/37179931/120622125-1e256000-c491-11eb-8374-b388f9beeb0b.png)

**Comment by Dopa4** [comment]
Is this caused by my wrong operation？

**Comment by mstorsjo** [comment]
That looks like you're running msys2, and you have installed the msys2 package `cmake` (which runs in the msys2 environment, which emulates unix/posix and thus thinks it's running on unix) - you need a plain windows version of cmake. Visual Studio comes with it integrated these days, so if you just run it from a Visual Studio Developer Prompt instead, it should work fine, or within msys2, you could install the `mingw-w64-x86_64-cmake` package (and make sure that `/mingw64/bin` is in path, i.e. running it in a mingw64 prompt, not a plain msys2 prompt).

**Comment by Dopa4** [comment]
Hello, I executed pacman - S mingw-w64-x86_ 64-cmake ，Installed to /mingw64 /bin path .
But I want to compile a 32-bit program and start mysy2 with mingw32.

**Comment by mstorsjo** [comment]
> Hello, I executed pacman - S mingw-w64-x86_ 64-cmake ，Installed to /mingw64 /bin path .
> But I want to compile a 32-bit program and start mysy2 with mingw32.

If you're in the mingw32 environment in msys, then you need to install `mingw-w64-i686-cmake` instead.

**Comment by Dopa4** [comment]
I have successfully compiled namake. Can I execute the command "nmake -- prefix=/ usr/local install" next?

**Comment by Dopa4** [comment]
I have successfully installed using the following command: cmake .. -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"

**Comment by mstorsjo** [comment]
Ok, so I guess this issue can be closed then?

**Comment by Dopa4** [comment]
You can turn off this issue
