### ISSUE TITLE
No executable generated

### ISSUE THREAD

**Issue by Dopa4** [mstorsjo/fdk-aac#136]
![image](https://user-images.githubusercontent.com/37179931/120636824-b2e38a00-c4a0-11eb-84b5-b7101362fc13.png)
![image](https://user-images.githubusercontent.com/37179931/120636861-c131a600-c4a0-11eb-8191-d42fd3b80bf6.png)

**Comment by mstorsjo** [comment]
You need to configure it with `-DBUILD_PROGRAMS=YES` to build the example tool.

**Comment by Dopa4** [comment]
Thanks problem has benn sloved

**Comment by Dopa4** [comment]
You can turn off this issue
