### ISSUE TITLE
Decoder skipping frames with some files using uniDRC

### ISSUE THREAD

**Issue by enzo1982** [mstorsjo/fdk-aac#140]
The decoder is skipping frames, returning AAC_DEC_PARSE_ERROR or AAC_DEC_DECODE_FRAME_ERROR for certain files making use of the uniDRC extension.

This is fixed upstream with commit [67cae74f](https://android.googlesource.com/platform/external/aac/+/67cae74f74bce961e0812c1743c64df96a3396b7%5E!/#F0).

I can provide an example via email if needed.

It would be great if the code here could be updated to include this fix.

**Comment by mstorsjo** [comment]
Yep, it's on my todo list to merge in the latest upstream dump. I'll try to see if I can bring it closer to the top of the todo list...

**Comment by enzo1982** [comment]
Yes, that fixes it. Thanks!
