### ISSUE TITLE
Potential incorrect memory access

### ISSUE THREAD

**Issue by jslarraz** [mstorsjo/fdk-aac#167]
Hi fdk-aac team! 

I was taking a look at the fdk-aac code and found what I think it might be an issue that I would like to confirm. 

The issue exists in function `CLatmDemux_ReadStreamMuxConfig` at file [tpdec_latm.cpp](https://github.com/mstorsjo/fdk-aac/blob/master/libMpegTPDec/src/tpdec_latm.cpp).

In this function `updateConfig` is defined and initialized as  `UCHAR updateConfig[1 * 1] = {0};`. It is then accessed in the loop indexed using TPDEC_TRACKINDEX(prog, lay), what should cause a memory corruption whenever this code is hit for for either prog or lay other than 0. (A similar issue also occurs with `pAscDummy`).

```
    for (UINT prog = 0; prog < pLatmDemux->m_numProgram; prog++) {
...
        for (UINT lay = 0; lay < pLatmDemux->m_numLayer[prog]; lay++) {
...
            if (!pLatmDemux->applyAsc) {
                updateConfig[TPDEC_TRACKINDEX(prog, lay)] = 0;
            } else {
                updateConfig[TPDEC_TRACKINDEX(prog, lay)] = 1;
            }
```

It would be great if you can take a look at it. 

Thanks!

**Comment by mstorsjo** [comment]
For context - I don't develop fdk-aac from scratch here. This is a codebase that is originally developed internally within Fraunhofer. They then release one version of that codebase as open source as part of the Android Open Source Project. I take the code from there and repackage it for use outside of Android.

So I don't know the codebase itself much, in general.

For this case, I don't know. I could try to ask someone at Fraunhofer about it. Do you have input that manages to trigger this case? In that case, it's a clear bug. If not, the code perhaps mostly seem surprising, but there can in many cases be other logical limits in the code that makes it never exceed such buffers (although, in this case, an array with 1 member does seem somewhat weird).

**Comment by jslarraz** [comment]
Hi @mstorsjo,

Thanks for your response! 

I've not triggered this case. I agree the code logic may ensure this case is never hit (as happens in several places in the code base like huff_read). However, this case is specially weird as the array only has 1 element and wondered if someone with more knowledge of the code could take a look at it to discard further implications.

Thanks again :)
