### ISSUE TITLE
Encoded file wrong length and speed.

### ISSUE THREAD

**Issue by kylophone** [mstorsjo/fdk-aac#23]
I'm trying to encode some audio and having a problem. A 10 second input file becomes 7.17 seconds after encoding. I can confirm that the input file is 48kHz PCM. Playing back the encoded file, I can hear that the entire file is there, but the playback rate is faster. If anybody has any ideas about what I've done wrong here, any help is appreciated. Here are my encoder parameters:

``` C
HANDLE_AACENCODER encoder_handle = NULL;
  if (aacEncOpen(&encoder_handle, 0, 2) != AACENC_OK) {
    fprintf(stderr, "Unable to open encoder\n");
    return 1;
  }
if (aacEncoder_SetParam(encoder_handle, AACENC_AOT, 2) != AACENC_OK) {
    fprintf(stderr, "Unable to set the AOT\n");
    return 1;
  }
  if (aacEncoder_SetParam(encoder_handle, AACENC_SAMPLERATE, 48000) != AACENC_OK) {
    fprintf(stderr, "Unable to set the sample rate\n");
    return 1;
  }
  if (aacEncoder_SetParam(encoder_handle, AACENC_CHANNELMODE, MODE_2) != AACENC_OK) {
    fprintf(stderr, "Unable to set the channel mode\n");
    return 1;
  }
  if (aacEncoder_SetParam(encoder_handle, AACENC_CHANNELORDER, 1) != AACENC_OK) {
    fprintf(stderr, "Unable to set the wav channel order\n");
    return 1;
  }
  if (aacEncoder_SetParam(encoder_handle, AACENC_BITRATE, 576000) != AACENC_OK) {
      fprintf(stderr, "Unable to set the bitrate\n");
      return 1;
    }
  if (aacEncoder_SetParam(encoder_handle, AACENC_TRANSMUX, 2) != AACENC_OK) {
    fprintf(stderr, "Unable to set the ADTS transmux\n");
    return 1;
  }
  if (aacEncoder_SetParam(encoder_handle, AACENC_AFTERBURNER, 1) != AACENC_OK) {
    fprintf(stderr, "Unable to set the afterburner mode\n");
    return 1;
  }
  if (aacEncEncode(encoder_handle, NULL, NULL, NULL, NULL) != AACENC_OK) {
    fprintf(stderr, "Unable to initialize the encoder\n");
    return 1;
  }
```

Here's what ffprobe says about the output file:

```
[aac @ 0x7f951980da00] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'out.aac':
Duration: 00:00:07.17, bitrate: 576 kb/s
Stream #0:0: Audio: aac, 48000 Hz, stereo, fltp, 576 kb/s
```

Thanks!

**Comment by mstorsjo** [comment]
Note the first line:
    [aac @ 0x7f951980da00] Estimating duration from bitrate, this may be inaccurate
That is, the duration is guessed based on the bitrate of one of the first frames in the file, together with the filesize.

Does it end up as the right duration (and speed) when you recode it back to a wav file?

**Comment by jaromanda** [comment]
I have similar code: the next 5 lines are critical
```C
	if (aacEncInfo(handle, &info) != AACENC_OK) {
		fprintf(stderr, "Unable to get the encoder info\n");
		return 1;
	}
	input_size = channels * 2 * info.frameLength;
```
**input_size** is the MAXIMUM number of bytes you can feed to aacEncEncode - it's not that simple, but read aac-enc.c to understand it.

As a test, I doubled input_size ... and my file length halved ... which would suggest if you feed too much to aacEncEncode, it just silently drops the excess.

by the way, usually, it will be 4096 with 2 channels ... you seem to be passing aacEncEncode somewhere in the vicinity of 5700 bytes (or 1428 samples). The rest of your code would shed light on what you're doing wrong

**Comment by kylophone** [comment]
Looks like this is exactly what was happening. However, the amount of bytes I can feed the encoder before it starts throwing away the extra is way lower than expected. It seems like 408 bytes is the maximum, which seems like a very odd number to me. Input buffers smaller than this encode just fine. 

```c
input_size = channels * 2 * info.frameLength; //evaluates to 4096 as expected
```

I'll continue to debug, and let everyone know if I figure anything else out.
