### ISSUE TITLE
Trouble with compiling aac-enc.c

### ISSUE THREAD

**Issue by fugokidi** [mstorsjo/fdk-aac#26]
I've trouble with compiling an example encoder. I linked with wavreader. But still no success. May I know the correct way to get aac-enc get running. I'm sorry for asking the compilation, I'm really in trouble. Thank you. What I did is
I run autoconf, ./configure, make
I run gcc -c -o wavreader.o wavreader.c
I run gcc aac-enc.c wavreader.o -o aac-enc
It failed.

**Comment by mstorsjo** [comment]
./configure --enable-example
    make

**Comment by fugokidi** [comment]
Thank you very much, it absolutely solves the problem. You guys are amazing.
