### ISSUE TITLE
configure.ac shows version 0.1.4 + Changelog's latest entry is 0.1.3

### ISSUE THREAD

**Issue by davidfavor** [mstorsjo/fdk-aac#28]
Be great to have a list of changes added in 0.1.4 when you have time.

Thanks!

**Comment by mstorsjo** [comment]
Thanks for the reminder - I'm planning to release 0.1.4 pretty soon, and this needs to be done before that.

I pushed a commit adding some notes on this now.

**Comment by davidfavor** [comment]
Great. I see the update now.

Also, might be good to place a note about the API change (ABI breakage) to say whether or not this effects ffmpeg, so people know whether to stay at 0.1.3 or move up to 0.1.4 when it releases.

Thanks.

**Comment by mstorsjo** [comment]
I don't think it is relevant to list all potential downstream users and to list whether they have updated their code to work with the new API (an information which will be oudated the second it is out there, for API users that haven't yet updated). Whether calling code X works with library Y or not, is something that X should document, not Y. For the record, yes, libavcodec works with the new version already before the new version was pushed to the master branch.

**Comment by mstorsjo** [comment]
I'll mention it in the release announcement, but I'm not adding it to the changelog in git.

**Comment by mstorsjo** [comment]
FWIW, 0.1.4 is released now, with the announcement at https://sourceforge.net/p/opencore-amr/mailman/message/33585271/.
