### ISSUE TITLE
decoder example

### ISSUE THREAD

**Issue by robotnic** [mstorsjo/fdk-aac#3]
I have many soundfiles in aac-eld format. (It was a mistake to use eld). Now I don't find a program that is aber to open this format.

A decoder example would be excellent.

**Comment by fugokidi** [comment]
Hello,
I've a little trouble with compiling decoder-example. I'm trying to analyzed quantized spectral coefficients. I want to decode aac stream(.aac). I don't need to deal with m4a. The compilation is giving me m4a error. Please guide me.
```
fdk-aac: make
  CCLD     m4a-dec
Undefined symbols for architecture x86_64:
  "_av_free_packet", referenced from:
      _main in m4a_dec-m4a-dec.o
  "_av_strerror", referenced from:
      _main in m4a_dec-m4a-dec.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [m4a-dec] Error 1
```
Thank you.

**Comment by mstorsjo** [comment]
If you you're testing the decoder-example branch and it fails for you, you can either try to checkout the second-last commit in that branch (before the m4a-dec tool was added, if that fails for you and you don't want to build it), or try configuring with `PKG_CONFIG=false ./configure --enable-example`, to make sure it doesn't detect libavformat and doesn't try to build m4a-dec.

**Comment by fugokidi** [comment]
Dear Sir,
Compilation is successful. But I'm getting shell script wrapper executable for aac-dec even though I compiled with --disable-shared. However, I got real binary for aac-enc. Thank you.

**Comment by mstorsjo** [comment]
Did you build without `--disable-shared` first? Make sure you do a full `make clean` (or ideally `make distclean`) if you reconfigure.

**Comment by fugokidi** [comment]
Yes, I did without it first, let me try now.

**Comment by fugokidi** [comment]
I ```make distclean```. I configured with --disable-shared. But only aac-dec becomes wrapper.

**Comment by mstorsjo** [comment]
I can't really help much with that, then - I get a proper binary and no shell script when building that way. What does `ldd .libs/aac-dec` say (or, on OS X, `otool -L .libs/aac-dec`)?

**Comment by fugokidi** [comment]
Sorry, I felt asleep, it was 3am. Now I nuked the whole folder, I checked out decoder-example again and build as you said, it's awesome. I'm good to go now. I'm not sure it's related to iTerm2 session or not. Maybe time to move to Linux. Thank you very much, you are the best.
