### ISSUE TITLE
Can't compile under visual studio 2015

### ISSUE THREAD

**Issue by ssc19940105** [mstorsjo/fdk-aac#30]
It shows:
Item severity code file line
Error C1021 Invalid preprocessor command "Warning " FDK - AAC C: \ Users \ Shen Shu super \ Download \ compression \ fdkaac \ FDK -AAC \ libfdk \ include \ FDK_archdef.h 218

**Comment by mstorsjo** [comment]
This should be fixed in 0.1.5.
