### ISSUE TITLE
Create git tag for new release: v0.1.5

### ISSUE THREAD

**Issue by jirutka** [mstorsjo/fdk-aac#45]
You’ve bumped version in a0bd8aa3b6339082fbe9d830264839fa50c0a4b7, but haven’t create a tag.

**Comment by mstorsjo** [comment]
Yes - this is intentional. I've bumped the version to signify that it contains new code, but I'm intentionally delaying tagging it as a new release until it has received more testing, in case there's something that needs fixing.

**Comment by cojj90** [comment]
I've been using this for few month now - looks pretty stable 👍

**Comment by Barough** [comment]
Any news/info when this will be tagged it as v0.1.5

**Comment by mstorsjo** [comment]
The dust has pretty much settled around these changes now, so I can try to make a release soon - thanks for reminding me!

**Comment by Barough** [comment]
That sounds great. :)

**Comment by mstorsjo** [comment]
Now 0.1.5 is tagged and a tarball is released.
