### ISSUE TITLE
always output not enough bits when decode AAC-LC.

### ISSUE THREAD

**Issue by xsjqqq123** [mstorsjo/fdk-aac#50]
Hello, I have record a aac file with many adts header. I read 320 bytes each time and put them into follow function in the picture, but never get output. Is there anything I was wrong?
![16 11 30 2217_1](https://cloud.githubusercontent.com/assets/8264121/20755689/db30ce68-b74a-11e6-8cc3-98192d9c6ad8.png)

**Comment by xsjqqq123** [comment]
just init the decoder:
handle = aacDecoder_Open(TT_MP4_ADTS, 1);

**Comment by mstorsjo** [comment]
Have a look at the `aac-dec.c` file in the `decoder-example` branch.

**Comment by xsjqqq123** [comment]
@mstorsjo thank you for your example, I had succeed decode my audio data. 
now I fall into encocoder problem. I use follow code to setup encoder, it success encode adts packet, but when I decode it use faad2, the samplerate becomes 32000 and channels becomes 2. My source pcm is just 16000 and mono, Is there anywhere I can set?

`if (aacEncoder_SetParam(handle->aacEncHandle, AACENC_SAMPLERATE, 16000) != AACENC_OK) {
    __ERR("Unable to set the sample rate\n");
    goto error;
}

if (aacEncoder_SetParam(handle->aacEncHandle, AACENC_CHANNELMODE, MODE_1) != AACENC_OK) {
    __ERR("Unable to set the channel mode\n");
    goto error;
}`

**Comment by mstorsjo** [comment]
No idea what's going wrong in your case - have you tested with the `aac-enc.c` example app, which can encode wav files into ADTS files? I don't think I've tested it with faad2, but it's been tested with a number of other decoders, and it works as it should there - I just tested it with the 16000/mono combo, played back with avplay.

**Comment by xsjqqq123** [comment]
It's not fdk-aac problem, the encoded packet is ok. faad2 decode packet and output 2 channel pcm data... thank you for your anser.

**Comment by xsjqqq123** [comment]
@mstorsjo  sorry for trouble you again. the encoded aac packet seems thow away some raw data. aacEncEncode dose not consume all the input buffer? and the rest data should calculate from AACENC_OutArgs and encode them again?

**Comment by mstorsjo** [comment]
Have a look at `aac-enc.c`. You can't pass arbitrary amount of data to the encoder, but you need to feed it data according to the frame length (`info.frameLength`). If you give it more data than the full frame size, it will ignore the rest. Only at the end, you can pass it an incomplete frame, and then pass `in_args.numInSamples = -1` to indicate that there won't be any more input data.

**Comment by xsjqqq123** [comment]
ok, I modify my code and test again, it looks like what I said and works well now .

other question,  can I output multi sampleRate packet when input data just 16000HZ?

**Comment by mstorsjo** [comment]
I'm not sure what you're asking - if you want to have a different sample rate, you need to resample it yourself before passing it to the encoder.

**Comment by xsjqqq123** [comment]
ok thank for you kindness.
