### ISSUE TITLE
Broken Documentation

### ISSUE THREAD

**Issue by a-rose** [mstorsjo/fdk-aac#55]
Hi,
I noticed aacEncoder.pdf is a bit broken in version 0.1.5: some code-formatted text is missing, see page 5 for an example. The same issue exists in the original FDK so it's not your fault, but maybe you could mention it somewhere, or replace the file with a non-broken one (from 0.1.4 for example) ?

(I'm viewing the file with Atril Document Viewer 1.8.1 on Ubuntu).

**Comment by mstorsjo** [comment]
I'd rather not change the file, deviating from upstream unnecessarily, but I can mention it to Fraunhofer.
