### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by f4bsch** [mstorsjo/fdk-aac#56]
Hi,
I added CMake support, see https://github.com/rtaudio/fdk-aac/blob/master/CMakeLists.txt .
Its currently tested with Visual Studio only, I'll add unix platform and create a pull request if there is interest.

**Comment by mstorsjo** [comment]
Thanks for the link! I do see the value of cmake for supporting visual studio better (currently we have a nmakefile only), but on the other hand I wouldn't want to duplicate the build systems either.

I'm not sure I'm willing to switch right now, but I'll keep it in mind!

**Comment by fcore117** [comment]
Lastest trend is more and more projects move to modern stand alone CMake. f4bsch good job helping to standardize CMake.

**Comment by 315583688** [comment]
Thanks for your CMake support!

**Comment by neheb** [comment]
Doesn't look like this installs pkgconfig files.

**Comment by Be-ing** [comment]
Implemented in #119. This issue can be closed.
