### ISSUE TITLE
Optimizing for ARM/NEON

### ISSUE THREAD

**Issue by trs79** [mstorsjo/fdk-aac#57]
I noticed that none of the files in libFDK/src/arm are included when compiling, is there any flag I need to set for these files to get included? I'm assuming those files need to be included to be fully optimized for ARM processors?

I'm trying to compile for a Raspberry PI 2, and when used with FFMPEG the cpu usage is ~80%. I'm hoping to get that down with a version compiled to take advantage of NEON.

**Comment by mstorsjo** [comment]
Those files aren't built standalone, but e.g. `libFDK/src/arm/qmf_arm.cpp` is included in `libFDK/src/qmf.cpp` if `__arm__` is defined (and that's defined by default when targeting arm).

There's actually no NEON code at all within fdk-aac, but only a few specially tuned C functions, and some inline assembly snippets. IIRC the most important ones performance wise are in `libFDK/include/arm/clz_arm.h`, `libFDK/include/arm/fixmul_arm.h` and `libFDK/include/arm/fixmadd_arm.h`. Those should be enabled by default when targeting raspberry pi/raspbian (they should all be available when targeting armv6 and newer, but if curious, try sticking e.g. an `#error` in those assembly snippets to see if they are included).

To speed up encoding, by sacrificing a little quality, add `-afterburner 0` to the encoder options in ffmpeg.
