### ISSUE TITLE
Missing bitrate information on encoded videos

### ISSUE THREAD

**Issue by moonchild-it** [mstorsjo/fdk-aac#58]
Hello, when i encode videos using this libraries (with ffmpeg or handbrake), the
output file is missing of information about encoded bitrate,

This cause various issues with several software.
I encode MKV files and I use Linux as OS.

Sorry for bad english.
Thanks in adavance and, in first, thanks for giving us a efficent aac encoder working also under linux.

Regards.

**Comment by mstorsjo** [comment]
This is not an issue with fdk-aac but with the application doing the encoding.

If encoding in CBR mode, the application should know the bitrate in advance. If encoding in VBR mode, the application needs to calculate the average bitrate from the encoding output and make sure that ends up written in the file, and both ffmpeg and handbrake might miss updating that. In that case, either make sure those applications update the bitrate properly afterwards, or encode in CBR mode instead.
