### ISSUE TITLE
Libtool library used but `LIBTOOL' is undefined

### ISSUE THREAD

**Issue by heas2-07** [mstorsjo/fdk-aac#6]
Hi

im trying to install this on centos 5. 

I run the following

git clone --depth 1 git://github.com/mstorsjo/fdk-aac.git
cd fdk-aac
autoreconf -fiv
./configure --disable-shared

but get the following error

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
Makefile.am:31: Libtool library used but`LIBTOOL' is undefined
Makefile.am:31:
Makefile.am:31: The usual way to define `LIBTOOL' is to add`AC_PROG_LIBTOOL'
Makefile.am:31: to `configure.ac' and run`aclocal' and `autoconf' again.
Makefile.am: C objects in subdir but`AM_PROG_CC_C_O' not in `configure.ac'
autoreconf: automake failed with exit status: 1

Can you advise on what I should be doing?

Thanks for any help

**Comment by Jamlee** [comment]
@mstorsjo it worked for me. i change `configure.ac` and  `Makefile.am` as you show.
