### ISSUE TITLE
GetAacDecoder() always return NULL

### ISSUE THREAD

**Issue by aifer2007** [mstorsjo/fdk-aac#64]
I port fdk-aac to a mcu.

When I create the aac decoder:
```C
/* Allocate AAC decoder core struct. */
  aacDec = CAacDecoder_Open(transportFmt);
```
In aacdecoder.cpp, CAacDecoder_Open calls GetAacDecoder() to create the decoder.

But GetAacDecoder() returns NULL all the time.

**Comment by mstorsjo** [comment]
That means that `FDKcalloc`, within the `C_ALLOC_MEM` macro, returns `NULL`. Then you need to debug that within your platform.

This is most probably not a bug in fdk-aac but in your environment and how you do the porting there.
