### ISSUE TITLE
How to run fdk-aac on MCU with samll RAM

### ISSUE THREAD

**Issue by aifer2007** [mstorsjo/fdk-aac#65]
After go into the fdk-aac's codes, I find that fdk-aac' data struct is designed for 8 channels as default.
For example, AAC_DECODER_INSTANCE has pcmOutputBuffer:
```C
INT_PCM      pcmOutputBuffer[(8)*(2048)];
```
AAC_DECODER_INSTANCE for 8 channels is large than 48K Bytes .

If we reduce channels to 2 , AAC_DECODER_INSTANCE is smaller then 24K Bytes. There are some  vars in some files can be changed from 8 channels to 2 channels to reduce the RAM needed by  fdk-aac.

If we only use stero audio , only 2 channels is ok. The fdk-aac can  run on MCU with small RAM.

But I find that I have to change much codes in some different files such as accdecoder/accdecoder_lib.cpp to fit ro 2 channels.

Is there some other way to reduce the RAM needed by fdk-aac？

**Comment by mstorsjo** [comment]
Not that I know of off-hand - to answer this, I would have to research it just as you would.
