### ISSUE TITLE
m4a-dec : Segmentation fault: 11 error

### ISSUE THREAD

**Issue by aifer2007** [mstorsjo/fdk-aac#68]
I compile the m4a-dec example and run it on Mac.
```
./m4a-dec in.m4a out.wav
```
 Segmentation fault: 11 error is reported.

**Comment by mstorsjo** [comment]
This gives me absolutely no clue to what actually goes wrong, because it works for me.

Make sure that the example actually runs with the same libavformat version that it was compiled with.

If this doesn't help, you need to debug it yourself to figure out what goes wrong.

**Comment by aifer2007** [comment]
@mstorsjo 
Great, you are right.
I reinstall libav and m4a-dec can work now.
