### ISSUE TITLE
is there a test suite for the library?

### ISSUE THREAD

**Issue by zhuker** [mstorsjo/fdk-aac#71]
if i wanted to change something in the library how do i make sure i dont break something unexpected?

**Comment by mstorsjo** [comment]
There's no official testsuite as such, but I created something that does some rudimentary encoding+decoding and comparing the difference - have a look in the `encode-decode-test` branch. If you run that twice, with a mono and stereo input wav, it should cover at least many of the common codepaths. (Make sure that the test passes before; it kinda depends on the input content.)

**Comment by zhuker** [comment]
thanks
