### ISSUE TITLE
Assert in fixpoint_math.cpp - libfdk-aac-0.1.5

### ISSUE THREAD

**Issue by 1045917067** [mstorsjo/fdk-aac#75]
(gdb) 
#0  0x00007f96698d4428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f96698d602a in __GI_abort () at abort.c:89
#2  0x00007f96698ccbd7 in __assert_fail_base (fmt=<optimized out>, 
    assertion=assertion@entry=0x7f966aac33a1 "L_denum > (FIXP_DBL)0", 
    file=file@entry=0x7f966aac3333 "libFDK/src/fixpoint_math.cpp", line=line@entry=547, 
    function=function@entry=0x7f966aac3600 <fDivNorm(int, int, int*)::__PRETTY_FUNCTION__> "FIXP_DBL fDivNorm(FIXP_DBL, FIXP_DBL, INT*)") at assert.c:92
#3  0x00007f96698ccc82 in __GI___assert_fail (assertion=assertion@entry=0x7f966aac33a1 "L_denum > (FIXP_DBL)0", 
    file=file@entry=0x7f966aac3333 "libFDK/src/fixpoint_math.cpp", line=line@entry=547, 
    function=function@entry=0x7f966a

ac3600 <fDivNorm(int, int, int*)::__PRETTY_FUNCTION__> "FIXP_DBL fDivNorm(FIXP_DBL, FIXP_DBL, INT*)") at assert.c:101
#4  0x00007f966aaa004c in fDivNorm (L_num=<optimized out>, L_denum=<optimized out>, result_e=<optimized out>)
    at libFDK/src/fixpoint_math.cpp:547
#5  0x00007f966aa40c76 in FDKaacEnc_AutoToParcor (input=input@entry=0x7ffda1bef990, 
    reflCoeff=reflCoeff@entry=0x7ffda1bef960, numOfCoeff=<optimized out>) at libAACenc/src/aacenc_tns.cpp:1150
#6  0x00007f966aa425bc in FDKaacEnc_TnsDetect (tnsData=tnsData@entry=0x3813ea4, tC=tC@entry=0x3814b8c, 
    tnsInfo=0x381a230, sfbCnt=49, spectrum=<optimized out>, subBlockNumber=subBlockNumber@entry=0, blockType=0)
    at libAACenc/src/aacenc_tns.cpp:818
#7  0x00007f966aa47e39 in FDKaacEnc_psyMain (channels=2, psyElement=0x3515e50, psyDynamic=<optimized out>, 
    psyConf=0x38145d0, psyOutElement=0x37c8ca0, pInput=pInput@entry=0x37e10b0, chIdx=0x3572588, totalChannels=2)
    at libAACenc/src/psy_main.cpp:805
#8  0x00007f966aa34019 in FDKaacEnc_EncodeFrame (hAacEnc=0x3572560, hTpEnc=0x37c8b20, inputBuffer=0x37e10b0, 
    nOutBytes=nOutBytes@entry=0x7ffda1bf05b0, extPayload=extPayload@entry=0x37e0748) at libAACenc/src/aacenc.cpp:769
#9  0x00007f966aa3fab7 in aacEncEncode (hAacEncoder=0x37e0610, inBufDesc=inBufDesc@entry=0x7ffda1bf0650, 
    outBufDesc=outBufDesc@entry=0x7ffda1bf0680, inargs=inargs@entry=0x7ffda1bf0620, outargs=outargs@entry=0x7ffda1bf0640)
    at libAACenc/src/aacenc_lib.cpp:1623

This happens 100% when I run 
./ffmpeg_g -i err_src.mp4 -vcodec libx264 -acodec libfdk_aac out.mp4

**Comment by mstorsjo** [comment]
Can you provide the input file that reproduces this issue?

**Comment by mstorsjo** [comment]
This should be fixed now in the latest git master version.
