### ISSUE TITLE
AAC ADTS Audio decoding issue

### ISSUE THREAD

**Issue by CoreTechie** [mstorsjo/fdk-aac#84]
Using the decoder example and the FDK-AAC library source from main branch, I tried decoding the following AAC encoded file (in ADTS Transport format) available at this link:
**https://samples.ffmpeg.org/A-codecs/AAC/ct_faac-adts.aac**

I choose TT_MP4_ADTS in the call to aacDecoder_Open()

But, the decoded WAV file that was dumped only plays noise and not the original sound. On close inspection, I see that in the output WAV file, the RIFF WAVE header is visible but the Data Bytes from offset 0x002C till 0x102B are all zeroes.

**Comment by mstorsjo** [comment]
I tested the `decoder-example` branch, built `aac-dec` and tried decoding this sample and it seems to work fine. I'm not sure if you're saying you built exactly this, or if you're saying you're trying to imlement something of your own, when you're saying "I choose TT_MP4_ADTS in the call to aacDecoder_Open()".

**Comment by CoreTechie** [comment]
I have uploaded my application main. 
[Main.zip](https://github.com/mstorsjo/fdk-aac/files/2129565/Main.zip)

and the bit-streams (the original .aac file and the decoded .wav file)
[Bitstreams.zip](https://github.com/mstorsjo/fdk-aac/files/2129566/Bitstreams.zip)

This is a Visual Studio 2017 solution (running on Intel) with two projects (application and the library). 

I am wondering where am I going wrong !

**Comment by mstorsjo** [comment]
I don't have time to try to debug your code for you. Since the code in the `decoder-example` branch works, you can try to build that and compare with your solution and figure out what is differing.

**Comment by CoreTechie** [comment]
We had cracked the issue. It was the size of **INT_PCM**. The decoder-example branch has it defined as SHORT, while the library I was working on had it defined as LONG. We have now taken the library source from the decoder-example branch. And it works perfectly !! Thank you very much for your help  !

**Comment by CoreTechie** [comment]
One more question:
Is the decoder capable of starting to parse the bits on a partial frame. I mean, even if the full audio frame is not filled by the aacDecoder_Fill() call ? I see that the aacDecoder_DecodeFrame() will return AAC_DEC_NOT_ENOUGH_BITS , but to what extent ? Is it that it needs the encoded bits of the whole audio frame to start its work (at least parsing) ?

**Comment by mstorsjo** [comment]
I would expect that it doesn't touch the data at all until it has got a complete ADTS frame, only then starts parsing/decoding it.

Closing this issue since it wasn't an issue with the library itself.
