### ISSUE TITLE
Cross-Compilation ubuntu->windows: libfdk_aac not found

### ISSUE THREAD

**Issue by konnextv** [mstorsjo/fdk-aac#88]
I am trying to compile fdk-aac on Ubuntu for mingw32. 

Compile fdk-aac:
`./configure --prefix="$HOME/ffmpeg_build" --host=i686-w64-mingw32 --target=mingw32 --disable-shared && make -j8 && make -j8 install`

This runs through, I only get one warning:
`WARNING: using cross tools not prefixed with host triplet`

Then I try to compile FFMPEG like this:
`./configure --prefix="$HOME/ffmpeg_build" --pkg-config-flags="--static" --arch=x86 --target-os=mingw32 --cross-prefix=i686-w64-mingw32- --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --extra-libs="-lpthread -lm" --bindir="$HOME/bin" --enable-libfdk-aac --enable-nonfree && make -j8 && make -j8 install && hash -r`

This runs into the error `libfdk_aac not found` and in the ffbuild/config.log it says:
`libfdk-aac.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status`

I already tried to rebuild the indexes of libfdk-aac.a, but that leads to other errors. From what others wrote about this error it seems like the files are compiled for the wrong system.

Any hints? Thanks in advance! :)

**Comment by mstorsjo** [comment]
Can you provide the full output from when you build fdk-aac; both from configure and from "make V=1" (to make the actual compile commands visible) - that'll allow me to make a more educated guess. Also, the `--target=mingw32` for configure is not necessary; for autoconf based projects, `--target` only makes sense when you are building a compiler.

**Comment by konnextv** [comment]
Output from ./configure: https://pastebin.com/R82jEzpm

Output from make V=1: https://pastebin.com/46iniyUn

thx =)

**Comment by mstorsjo** [comment]
The root cause seems to be that you only have got C compilers for `i686-w64-mingw32`, not the C++ compilers. Key part from the configure log:

```
configure:3065: checking for i686-w64-mingw32-gcc
configure:3081: found /usr/bin/i686-w64-mingw32-gcc
configure:3092: result: i686-w64-mingw32-gcc
```
```
configure:4110: checking for i686-w64-mingw32-g++
configure:4140: result: no
configure:4110: checking for i686-w64-mingw32-c++
configure:4140: result: no
configure:4154: checking for g++
configure:4170: found /usr/bin/g++
configure:4181: result: g++
configure:4197: WARNING: using cross tools not prefixed with host triplet
```

So autoconf chose to use the host C++ compiler instead of the cross triplet prefixed one, since it didn't find any such, and chose to warn you about it since it seems suspect.
