### ISSUE TITLE
FDK-AAC Decode and FFMPEG Decode WAVE files differ

### ISSUE THREAD

**Issue by CoreTechie** [mstorsjo/fdk-aac#91]
When I compare the decoded wave files from both fdk-aac decoder and ffmpeg decoder, i see a lot of differences in the hex output. Though, there is no such obvious audible differences in the playback of both the files, I am wondering why are they producing two different binary output ? The larger HEX differences are visible in the data chunks of the wave file.

The files attached.
[Files.zip](https://github.com/mstorsjo/fdk-aac/files/2282807/Files.zip)

**Comment by mstorsjo** [comment]
AAC is not defined to be bitexact. The ffmpeg decoder uses floating point, while the fdk-aac decoder uses fixed point. There is some amount of rounding in the decoding process so it is not expectd that each decode result will be identical; in most cases each sample value should be pretty close to each other, but I'm not sure if there even is some guarantee to that, as long as the end result sounds similar.

**Comment by CoreTechie** [comment]
Ok, understood. I see in most cases the sample differences are quite significant. But anyways the audio playback is similar.
