### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by birdie-github** [mstorsjo/fdk-aac#99]
When can we expect it?

**Comment by mstorsjo** [comment]
Good question; I guess the dust has settled around it now, the primary regressions wrt fuzz testing have been found and many projects using it are ready for the updated API, so I guess I could start doing the release soon.

**Comment by mstorsjo** [comment]
Now I've tagged the 2.0.0 release, and uploaded a source tarball to sourceforge: https://sourceforge.net/projects/opencore-amr/files/fdk-aac/
